### ISSUE TITLE
Patches to disable inlining of certain functions

### ISSUE THREAD

**Issue by ViralBShah** [MersenneTwister-Lab/dSFMT#2]
We apply the following patches to the dSFMT that ships with Julia.

https://github.com/JuliaLang/julia/blob/master/deps/patches/dSFMT.h.patch
https://github.com/JuliaLang/julia/blob/master/deps/patches/dSFMT.c.patch

If we were to submit a patch to the Makefiles that makes it possible to apply these patches with a flag, would that be acceptable? I know the package has not seen releases for a very long time, and perhaps this repo is only for archival purposes. This is why I ask before submitting anything further.

Thank you.

**Comment by MSaito** [comment]
Yes, we can accept your Makefile patch.
We should do
1) change Makefile with your patch
2) do NOT execute make with your flag
3) version update
4) add new version tag
Is this right?

**Comment by ViralBShah** [comment]
Yes, that is perfect!
